<div id="main-content">
    <section class="content-area">
       <div class="container site-content no-padding-top">
           <div class="row">
               <main id="main" class="site-main col-sm-12 full-width">
                <article class="post-2901 page type-page status-publish hentry pmpro-has-access">
                    <div class="entry-content">
                        <div class="panel-grid">
                            <div class="panel-grid-cell" id="pgc-2901-0-0">
                                <div class="so-panel widget widget_heading panel-first-child panel-last-child" id="panel-2901-0-0-0" data-index="0">
                                    <div style="" class="panel-widget-style">
                                        <div class="thim-widget-heading thim-widget-heading-base">
                                            <div class="sc_heading text-center">
                                                <h3 class="title">Terms and Conditions</h3>
                                                
                                                <span class="line"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-grid">
                            <div class="panel-grid-cell">
                                <div class="so-panel widget widget_counters-box panel-first-child panel-last-child">
                                    <div class="thim-widget-counters-box thim-widget-counters-box-base">
                                        <div class="panel-grid-cell">
                                            <div class="so-panel widget widget_text panel-first-child panel-last-child">                                                <div class="textwidget">This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that requires publishing the rules and regulations, Privacy Policy and Terms of Use for access or usage of our Website/App www.deliverystar.in ("Website/App") and for the mobile application Delivery Star Food Delivery("App")<br><br></div>
                                                <div class="textwidget">For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who visits our platform, either just for the purpose of browsing the Website/App/App or engages to buy our products. The term "We", "Us", "Our" shall mean Delivery Star Food Services ("Delivery Star").<br><br></div>
                                                <div class="textwidget">These Terms of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content. Please read these Terms of Service carefully before accessing or using Our Website/App. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website/App or use any services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service. Any new features or tools which are added to the current store shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to Our Website/App. It is your responsibility to check this page periodically for changes. Your continued use of or access to the Website/App following the posting of any changes constitutes acceptance of those changes.<br><br></div>
												<h3 class="widget-title">SECTION 1 - GENERAL CONDITIONS</h3>
                                                <div class="textwidget">1.1 By agreeing to these Terms of Service, You represent that you are at least 18 (Eighteen) years of age and you have given us your consent to allow any of your minor dependents to use this site. You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws). You must not transmit any worms or viruses or any code of a destructive nature. A breach or violation of any of the Terms will result in an immediate termination of your Services.<br><br>
                                                1.2 We reserve the right to refuse service to anyone for any reason at any time. You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks. You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the Website/App through which the service is provided, without express written permission by us. The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.<br><br></div>
                                                <h3 class="widget-title">SECTION 2 - MODIFICATIONS TO THE SERVICE AND PRICES</h3>
                                                <div class="textwidget">2.1 Prices for our products are subject to change without notice. We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time. We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.<br><br></div>
                                                <h3 class="widget-title">SECTION 3 - PRODUCTS OR SERVICES</h3>
                                                <div class="textwidget">3.1 Certain products or services may be available exclusively online through the Website/App. These products or services may have limited quantities and are subject to return or exchange only according to Our Return Policy. We reserve the right, but are not obligated, to limit the sales of Our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at any time without notice, at our sole discretion. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited. We do not warrant that the quality of any products, services, information, or other material purchased or obtained by You will meet your expectations, or that any errors in the Service will be corrected.<br><br></div>
                                                <h3 class="widget-title">SECTION 4 - ACCURACY OF BILLING AND ACCOUNT INFORMATION</h3>
                                                <div class="textwidget">4.1 We reserve the right to refuse any order you place with Us. We may, at our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that We make a change to or cancel an order, We may attempt to notify You by contacting the e-mail and/or billing address/phone number provided at the time the order was made. You agree to provide current, complete and accurate purchase and account information for all purchases made at Our store.<br><br></div>
                                                <h3 class="widget-title">SECTION 5 - OPTIONAL TOOLS</h3>
                                                <div class="textwidget">5.1 We may provide You with access to third-party tools which are different payment gateways over which We neither monitor nor have any control nor input. You acknowledge and agree that We provide access to such tools "as is" and "as available" without any warranties, representations or conditions of any kind and without any endorsement.<br><br>
5.2 We shall have no liability whatsoever arising from or relating to your use of optional third-party tools. Any use by You of optional tools offered through the site is entirely at your own risk and discretion and You should ensure that You are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s). We may also, in the future, offer new services and/or features through the Website/App (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service.
<br><br></div>
                                                <h3 class="widget-title">SECTION 6 - THIRD-PARTY LINKS</h3>
                                                <div class="textwidget">6.1 Certain content, products and services available via our Service may include materials from third- parties. Third-party links on this site may direct you to third-party Website/Apps that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or Website/Apps, or for any other materials, products, or services of third-parties. We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party Website/Apps<br><br>
6.2 Please review carefully the third-party's policies and practices and make sure You understand them before You engage in any transaction. Complaints, claims, concerns, or questions regarding third- party products should be directed to the third-party.
<br><br></div>
                                                <h3 class="widget-title">SECTION 7 - PERSONAL INFORMATION</h3>
                                                <div class="textwidget">7.1 Your submission of personal information through the Webiste/App is governed by our Privacy Policy. To view our Privacy Policy.<br><br></div>
                                                <h3 class="widget-title">SECTION 8 - ERRORS, INACCURACIES AND OMISSIONS</h3>
                                                <div class="textwidget">8.1 Occasionally there may be information on Our site or in the service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the service or on any related Website/App is inaccurate at any time without prior notice (including after You have submitted your order). We undertake no obligation to update, amend or clarify information in the Service or on any related Website/App, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related Website/App, should be taken to indicate that all information in the Service or on any related Website/App has been modified or updated.<br><br></div>
                                                <h3 class="widget-title">SECTION 9- PROPRIETARY RIGHTS</h3>
                                                <div class="textwidget">9.1 All materials on the Website/App, including, without limitation, names, logos, trademarks, images, text, columns, graphics, videos, photographs, illustrations, artwork, software and other elements (collectively, "Material") are protected by copyrights, trademarks and/or other intellectual property rights owned and controlled by Delivery Star. You acknowledge and agree that all Material on the Website/App is made available for limited, non-commercial, personal use only. Except as specifically provided herein or elsewhere in the Website/App, no Material may be copied, reproduced, republished, sold, downloaded, posted, transmitted, or distributed in any way, or otherwise used for any purpose, by any person or entity, without express written permission of Delivery Star. You may not add, delete, distort, or otherwise modify the Material. Any unauthorized attempt to modify any Material, to defeat or circumvent any security features, or to utilize the App or any part of the Material for any purpose other than its intended purposes is strictly prohibited.<br><br>
9.2 The Website/App may not be used in connection with any commercial purposes, except as specifically approved by Delivery Star.
<br><br></div>
                                                <h3 class="widget-title">SECTION 10 - PROHIBITED USE</h3>
                                                <div class="textwidget">10.1 In addition to other prohibitions as set forth in the Terms of Service, You are prohibited from using the site or its content: <br>
(a) for any unlawful purpose; <br>
(b) to solicit others to perform or participate in any unlawful acts; <br>
(c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; <br>
(d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; <br>
(e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; <br>
(f) to submit false or misleading information; <br>
(g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related Website/App, other Website/Apps, or the Internet; <br>
(h) to collect or track the personal information of others; <br>
(i) to spam, phish, pharm, pretext, spider, crawl, or scrape; <br>
(j) for any obscene or immoral purpose; or <br>
(k) to interfere with or circumvent the security features of the service or any related Website/App, other Website/Apps, or the Internet. We reserve the right to terminate your use of the service or any related Website/App for violating any of the prohibited uses.
<br><br></div>
                                                <h3 class="widget-title">SECTION 11 - DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</h3>
                                                <div class="textwidget">11.1 We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free. We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable. You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to You. You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to You through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement. In no case shall We, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility.<br><br></div>
                                                <h3 class="widget-title">SECTION 12 – INDEMNIFICATION</h3>
                                                <div class="textwidget">12.1 You agree to indemnify, defend and hold harmless Us and Our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.<br><br></div>
                                                <h3 class="widget-title">SECTION 13 – SEVERABILITY</h3>
                                                <div class="textwidget">13.1 In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.<br><br></div>
                                                <h3 class="widget-title">SECTION 14 - GOVERNING LAW</h3>
                                                <div class="textwidget">14.1 These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India and shall be subject to the jurisdiction of the courts in Vellore.<br><br></div>
                                                <h3 class="widget-title">SECTION 15- CANCELLATION AND REFUND POLICY</h3>
                                                <div class="textwidget">15.1 The cancellation of any order made by You should be cancelled within 6 (Ten) minutes of placing the order. Any cancellation made after such period of 6 minutes shall not be entertained and We shall be entitled to receive the entire amount of the order placed by You.<br><br>
15.2 However, in the unlikely event of an item on your order being unavailable, we will contact you on he phone number provided to us at the time of placing the order and inform you of such unavailability. In such an event you will be entitled to cancel the entire order and shall be entitled to a refund in accordance with our refund policy.<br><br>
We reserve the sole right to cancel your order in the following circumstance:<br><br>
I.	in the happening of the chosen address falls outside the delivery zone offered by us;<br>
II.	failure to contact you by phone at the time of confirming the order booking;<br>
III.	unavailability of all the items ordered by you at the time of booking the order; <br>
IV.	failure to deliver your order due to lack of information, direction or authorization from you at the time of delivery<br><br>
15.3 We are sure you would love our food. In case you were not happy with your Delivery Star meal, let us know at contact@Delivery Star.in. Delivery Star reserves the right to refund the entire amount for the order.
<br><br></div>
                                                <h3 class="widget-title">SECTION 16- GENERAL</h3>
                                                <div class="textwidget">16.1 We reserves the right to amend this Terms of Use at any time and without notice, and it is your responsibility to review this Terms of Use for any changes. Your use of the Website/App following any amendment of this Terms of Use will signify your assent to and acceptance of its revised terms.<br><br>
16.2 In case of any grievance arising from the use of the Website/App, please contact the Grievance Officer within 24 hours and the same shall be redressed within 48 hours from receipt of such complaint.
Last Updated on: Date
<br><br></div>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                    
                            </div>           
                        </div><!-- .entry-content -->
                     </div>
                 </article><!-- #post-## -->
                </main>
            </div>
        </div> 
    </section>
</div>