<div id="main-content">
    <section class="content-area">
       <div class="container site-content no-padding-top">
           <div class="row">
               <main id="main" class="site-main col-sm-12 full-width">
                <article class="post-2901 page type-page status-publish hentry pmpro-has-access">
                    <div class="entry-content">
                        <div class="panel-grid">
                            <div class="panel-grid-cell" id="pgc-2901-0-0">
                                <div class="so-panel widget widget_heading panel-first-child panel-last-child" id="panel-2901-0-0-0" data-index="0">
                                    <div style="" class="panel-widget-style">
                                        <div class="thim-widget-heading thim-widget-heading-base">
                                            <div class="sc_heading text-center">
                                                <h3 class="title">Privacy Policy</h3>
                                                
                                                <span class="line"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-grid">
                            <div class="panel-grid-cell">
                                <div class="so-panel widget widget_counters-box panel-first-child panel-last-child">
                                    <div class="thim-widget-counters-box thim-widget-counters-box-base">
                                        <div class="panel-grid-cell">
                                            <div class="so-panel widget widget_text panel-first-child panel-last-child">
                                                <div class="textwidget">This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.<br><br>
For the purpose of these Privacy Policy, Wherever the context so required you or user shall mean any natural or legal person who visits our platform, either just for the purpose of browsing WWW.deliverystar.in (our "Website") website or engages to buy our product. The term We, Us, Our shall mean Delivery Star Food Services ("Delivery Star").<br><br></div>
                                                <h3 class="widget-title">Section 1 – What Information do we collect</h3>
                                                <div class="textwidget">Personal Data: We collect personal data from you when you voluntarily provide such information, such as when you contact us to place order for our products or to inquire about any information, respond to one of our surveys, which typically includes your<br><br>
                                                • Name<br>
												• Telephone Number<br>
                                                • Email Address<br>
                                                • Home Address<br>
                                                • Information about your home which you give us<br>
                                                • Your payment details<br>
                                                • Your IP address and<br>
                                                • Any other personal information which you give us in connection with the Services.<br>
												• Wherever We collect personal data we make an effort to provide a link to this Privacy Policy. If You send us personal correspondence, such as emails or letters, we may collect such information into a file specific to You.<br>
URLs: In general, You can browse our Website without telling Us who You are or revealing any personal information about yourself. Once You give us your personal information, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information for the fields that are optional. We may automatically track certain information about You based upon your behavior on Our Website. We use this information to do internal research on Our users' demographics, interests, and behavior to better understand, protect and serve Our users.<br><br>
												This information is compiled and analysed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Website or not), which URL You next go to (whether this URL is on Our Website or not), your browser information, and your IP address.<br><br>
												Cookies: We use data collection devices such as cookies on certain pages of the Website to help analyse our web page flow, measure promotional effectiveness, and promote trust and safety. Cookies are small files placed on your hard drive that assist us in providing our services. We offer certain features that are only available through the use of a cookie. Most cookies are session cookies, meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline our cookies if your browser permits. Additionally, you may encounter cookies or other similar devices on certain pages of the Website that are placed by third parties. We do not control the use of cookies by third parties.<br><br>
												The cookies used by us are listed as follows for your information to opt-out of cookies or not.<br><br>
												• _session_id, unique token, sessional, Allows Delivery Star to store information about your session (referrer, landing page, etc)<br>
                                                • provider's internal stats tracker to record the number of visits<br>
                                                • _secure_session_id, unique token, sessional storefront_digest, unique token, indefinite If the shop has a password, this is used to determine if the current visitor has access.<br>
                                                • Your payment details<br>
                                                • Your IP address and<br>
                                                • Any other personal information which you give us in connection with the Services.<br>
                                                • Wherever We collect personal data we make an effort to provide a link to this Privacy Policy. If You send us personal correspondence, such as emails or letters, we may collect such information into a file specific to You.<br><br>
                                                Payment Information: If You transact with Us, We collect some additional information, such as a billing address, a credit / debit card number and a credit / debit card expiration date and/ or other payment instrument details and tracking information from cheques or money orders.<br><br></div>
                                                <h3 class="widget-title">SECTION 2: WHAT DO WE DO WITH YOUR INFORMATION</h3>
                                                <div class="textwidget">2.1 We use personal information to provide the delivery of Our products to You. To the extent We use your personal information to market to You, We will provide You the ability to opt-out of such uses. We use your personal information to resolve disputes; troubleshoot problems; help promote a safe transaction; collect money; measure consumer interest in Our products, inform You about online and offline offers, products and updates; customize your experience; detect and protect Us against error, fraud and other criminal activity; enforce Our terms and conditions; and as otherwise described to You at the time of collection.<br><br>
2.2 In Our efforts to continually improve Our product offerings, We collect and analyse demographic and profile data about Our Users' activity on Our Website. We identify and use your IP address to help diagnose problems with Our server, and to administer Our Website. Your IP address is also used to help identify You and to gather broad demographic information.<br><br>
</div>
												<h3 class="widget-title">SECTION 3 - CONSENT</h3>
                                                <div class="textwidget">3.1 When You provide Us with personal information to complete a transaction, verify your credit card, place an order, arrange for a delivery or return a purchase, it is deemed that You have consented to the use of your personal information by Us to carry out the transaction as requested.<br><br>
3.2 In the course of business, if your personal information for any secondary reason, We shall specify the reason for requiring such information. Upon such request, You shall have the option to refrain from revealing such information to Us.<br><br>
3.3 If after You consent, either impliedly or expressly, for your personal information to be used by Us, You change your mind, You may withdraw your consent for Us to contact You, for the continued collection, use or disclosure of your information, at any time. Such withdrawal of consent shall be communicated to Us either through an email at contact@Delivery Star.in or by contacting Us at our at our corporate office.<br><br>
</div>
												<h3 class="widget-title">SECTION 4 - DISCLOSURE OF PERSONAL INFORMATION</h3>
                                                <div class="textwidget">4.1 We may share personal information with our other corporate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of Our Website; and to facilitate joint or co-branded services where such services are provided by more than one corporate entity. Those entities and affiliates may not market to You as a result of such sharing unless You explicitly opt-in.<br><br>
4.2 We may disclose personal information of You if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to enforce our Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our Users or the general public.<br><br></div>
                                                <h3 class="widget-title">SECTION 5 - DELIVERY STAR</h3>
                                                <div class="textwidget">1. All direct payment gateways adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover.<br>
2. PCI-DSS requirements help ensure the secure handling of credit card information by Our store and its service providers.<br><br>
3. For more insight, you may also want to read Delivery Star's Terms of Service here or Privacy Statement here.<br><br></div>
                                                <h3 class="widget-title">SECTION 6 - THIRD-PARTYSERVICES</h3>
                                                <div class="textwidget">6.1 We may engage the services of third parties to help us serve Our customers better. In general, the third-party services providers engaged by Us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to Us.<br><br>
6.2 However, certain third-party service providers, such as payment gateways and other payment transaction processors, have their own privacy policies in respect to the information We are required to provide to them for your purchase-related transactions and we recommend that You read their privacy policies so You can understand the manner in which your personal information will be handled by these third party service providers.<br><br>
6.3 In particular, remember that certain providers may be located in or have facilities that are located a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.<br><br>
6.4 Once you leave Our website or are redirected to a third-party website or application, You are no longer governed by this Privacy Policy or our website's Terms of Service.<br><br>
6.5 When you click on third party links on Our Website, We are not responsible for the privacy practices of other sites and for the loss or consequential damage that may be caused to you and encourage You to read their privacy statements.<br><br></div>
												<h3 class="widget-title">SECTION 7 - SECURITY</h3>
                                                <div class="textwidget">7.1 To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.<br><br>
7.2 If You provide Us with your credit card information, the information is encrypted using secure socket layer technology (SSL) and stored with a AES-256 encryption. Although, no method of transmission over the Internet or electronic storage is 100% secure, we follow all PCI-DSS requirements and implement additional generally <br><br></div>
                                                <h3 class="widget-title">SECTION 8 - AGE OF CONSENT</h3>
                                                <div class="textwidget">8.1 By using this site, You represent that You are at least the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.<br><br></div>
                                                <h3 class="widget-title">SECTION 9 - CHANGES TO THIS PRIVACY POLICY</h3>
                                                <div class="textwidget">9.1 We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the Website. If We make material changes to this policy, We will notify You here that it has been updated, so that You are aware of what information We collect, how we use it, and under what circumstances, if any, We use and/or disclose it.<br><br>
9.2 If our Website is acquired or merged with another company, your information may be transferred to the new owners so that we may continue to sell products to You.<br><br></div>
                                                <h3 class="widget-title">CONTACT INFORMATION:</h3>
                                                <div class="textwidget">For any query, grievance, complaint or any other information that may be required by You, You may contact Our Privacy Compliance Officer at contact@DeliveryStar.in and We shall ensure that We help resolve the same within a period of 48 (forty eight) hours.<br><br></div>
                                            </div>
                                        </div>
                                    </div>
                                    
                            </div>           
                        </div><!-- .entry-content -->
                    </article><!-- #post-## -->
                </main>
            </div>
        </div> 
    </section>
</div>